name: delivery
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  # sdk: ^3.7.2
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.3.3
  adaptive_theme: ^3.6.0
  flutter_spinkit: ^5.2.1
  animated_bottom_navigation_bar: ^1.3.3
  dio: ^5.7.0
  fluttertoast: ^8.2.10
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.3
  get: ^4.6.6
  bloc: ^9.0.0
  # onesignal_flutter: ^5.0.4
  meta: ^1.15.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  cached_network_image: ^3.4.1
  qr_flutter: ^4.1.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.4
  smooth_page_indicator: ^1.2.1
  connectivity_plus: ^6.1.4
  flutter_native_splash: ^2.4.6
  google_maps_flutter: ^2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    # - assets/localazations/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SFProText-Bold
      fonts:
        - asset: assets/fonts/pro/SFProText-Bold.ttf
    - family: SFProText-Regular
      fonts:
        - asset: assets/fonts/pro/SFProText-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: Cairo-Bold
      fonts:
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
